name: "Terraform_workflow"
# color for Github runner output
env:
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1
  
# Default to bash
defaults:
  run:
    shell: bash

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  ## pull_request:
    ## branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-connectivity:
    runs-on: self-hosted
    steps: 
      - run: |
          ping -c 2 10.88.36.23 
  validate-playbooks:
    needs: check-connectivity
    runs-on: self-hosted 
    steps: 
      - uses: actions/checkout@v3
      - run: |
           terraform init
  deploy-playbooks:
    needs: [check-connectivity, validate-playbooks]
    runs-on: self-hosted
    environment: deploy-to-apic
    steps: 
      - uses: actions/checkout@v3
      - run: |
           terraform apply --auto-approve
